language: java
jdk:
- oraclejdk8
#deploy:
#  provider: openshift
#  user: 
#    secure: "eJ2n0CkwC3N87em9r/AOOxXxrNrt2OAcBhXp+Xso8K/7b/nrNaVLo2G9jiIuXAdIm791OBfuo2cMEWa9fpXkV7KrxyrqpYplDSS4P1nErV3FSA94tzbVG6+mlIxYqb7dyIzv0LXPpy2X8jggUAHegyuB6GIjIkZvkaOXGDv1c47RVmBJvWeyfSRXiIQH/HYGSFhfbJXud9lo2tbGish6MBxhgLNIyG0ZFED1KOp+4kkMEFvkMIt3tz2Wh1HVRtv3ANY6qo4f7An/3xiQXe22npng2HrL8al5m0382ZGSb3iVLok32rmPlJkUXPBWDjOB/c1IaVMxsTu/eYwQad8+Qg8svrj3OIjRdmTXOhdrR9z9XvdOe6iUM/SGNcau+950teCpawu8EkrwGMTANBrKdQIoBVd1e3MAMCqZI+YWNUc0B/cT7j4bLQlrSAPuGPk4NQ8+XIk2Z8jWxGTBlDkh/Sz3Ew4p6d3L0yuTYTJx78NQOMcWJYEYK/6o/qohkdljBmAb8USjm9c6DAwDkylb/ESqWFiWE0/cFmyvMs3gxw6Jik2WBft4T/TLyhp5dMdRugZpKIWNld81x6+DOceH8dBnX1CWssG1tzOHAwSwnRln0YV0bwDVBxASY/X0Jfyj7z6irQxEZ1okvg0eIkHNBE0NNbvsmJlcKooEpzq/4aY=" 
#  password:
#    secure: Ouc3N6DAhbNLd1EA+Egep6MGLV5TPkOW9MydFgHEqA3VaDm8WqgQHduek/L5ome+ENQxoT/8BfYSGHSDtAAqRBejMI3B2KKHt4hPRe69tvoiX9qjXjO6jmj8Yj2TWFBS9P6Ck9z97S+luTxMJBYPWxf+/msdgnMQk61rdzAcYorfkq8VVSn8Ves2q8QewGvCJUuKXJ+Crqhh5rVU08fdJsL/xXqDueR2lqojzxpgMXkAxGLNSj6iT7+Kgada0F5b8HPnC/RT853rxTSlRt9ug/DzS3rWVdQfT+QSMkFubi76l35e37f4KORoSvFK1Zcchhn6RgbPr2oT18N+OYVXrtHwkf8P/TqY2+Ots/hDxZ3Bf0TWs5RVky+i2m5MH/FKKIDbkmRdoQCOnEdYV0I4/cn8zRF0cd3S71evkd2LobtGHlPd+87B6O1lG3AgPI37dKoorKDNbv2vubv1EkzXageAYTLxN6xvYMUuIGjemVFaic7tnSgzWnv6Unu57Ef7zlOb23ZWTp+R+c34LXMs+mj/dpaQzDdeWWMSJ4l3Zf2bJK9hRp1pcD6rOI/y64b1wPGt8JKFmfR28uuplWlT08hNv7r/QFvBpkzg66fKwVOxLi52IWnN1JPC/yGpjYB6cGhUy4v+dqvQOtlRFag+rQ83GIesSFAT/iw22O88ZLE=
#  app: broker
#  domain: olaldiko
#  on:
#    repo: POPBL-6/broker
